//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letterstocrushes.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookmark
    {
        public int BookmarkId { get; set; }
        public System.DateTime AddDate { get; set; }
        public System.DateTime RevisedDate { get; set; }
        public int Visible { get; set; }
        public int LetterId { get; set; }
        public int Type { get; set; }
        public string UserGuid { get; set; }
    }
}
