//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letterstocrushes.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat_visitors
    {
        public int id { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string nickname { get; set; }
    }
}
