//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letterstocrushes.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int Id { get; set; }
        public string commentMessage { get; set; }
        public string commenterName { get; set; }
        public int letterId { get; set; }
        public bool sendEmail { get; set; }
        public System.DateTime commentDate { get; set; }
        public int hearts { get; set; }
        public string commenterEmail { get; set; }
        public string commenterIP { get; set; }
        public string commenterGuid { get; set; }
        public Nullable<int> level { get; set; }
    }
}
