//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letterstocrushes.Infrastructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class db_mysql : DbContext
    {
        public db_mysql()
            : base("name=db_mysql")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<block> blocks { get; set; }
        public DbSet<chat_visitors> chat_visitors { get; set; }
        public DbSet<chat> chats { get; set; }
        public DbSet<comment> comments { get; set; }
        public DbSet<song> songs { get; set; }
        public DbSet<letter> letters { get; set; }
    
        public virtual ObjectResult<letter> quickSearch(string search_terms)
        {
            var search_termsParameter = search_terms != null ?
                new ObjectParameter("search_terms", search_terms) :
                new ObjectParameter("search_terms", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<letter>("quickSearch", search_termsParameter);
        }
    
        public virtual ObjectResult<letter> quickSearch(string search_terms, MergeOption mergeOption)
        {
            var search_termsParameter = search_terms != null ?
                new ObjectParameter("search_terms", search_terms) :
                new ObjectParameter("search_terms", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<letter>("quickSearch", mergeOption, search_termsParameter);
        }
    
        public virtual ObjectResult<letter> searchLettersByDate(string search_terms, Nullable<int> search_year, Nullable<int> search_month, Nullable<int> search_day)
        {
            var search_termsParameter = search_terms != null ?
                new ObjectParameter("search_terms", search_terms) :
                new ObjectParameter("search_terms", typeof(string));
    
            var search_yearParameter = search_year.HasValue ?
                new ObjectParameter("search_year", search_year) :
                new ObjectParameter("search_year", typeof(int));
    
            var search_monthParameter = search_month.HasValue ?
                new ObjectParameter("search_month", search_month) :
                new ObjectParameter("search_month", typeof(int));
    
            var search_dayParameter = search_day.HasValue ?
                new ObjectParameter("search_day", search_day) :
                new ObjectParameter("search_day", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<letter>("searchLettersByDate", search_termsParameter, search_yearParameter, search_monthParameter, search_dayParameter);
        }
    
        public virtual ObjectResult<letter> searchLettersByDate(string search_terms, Nullable<int> search_year, Nullable<int> search_month, Nullable<int> search_day, MergeOption mergeOption)
        {
            var search_termsParameter = search_terms != null ?
                new ObjectParameter("search_terms", search_terms) :
                new ObjectParameter("search_terms", typeof(string));
    
            var search_yearParameter = search_year.HasValue ?
                new ObjectParameter("search_year", search_year) :
                new ObjectParameter("search_year", typeof(int));
    
            var search_monthParameter = search_month.HasValue ?
                new ObjectParameter("search_month", search_month) :
                new ObjectParameter("search_month", typeof(int));
    
            var search_dayParameter = search_day.HasValue ?
                new ObjectParameter("search_day", search_day) :
                new ObjectParameter("search_day", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<letter>("searchLettersByDate", mergeOption, search_termsParameter, search_yearParameter, search_monthParameter, search_dayParameter);
        }
    }
}
