//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letterstocrushes.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class letter
    {
        public int Id { get; set; }
        public string letterMessage { get; set; }
        public string letterTags { get; set; }
        public System.DateTime letterPostDate { get; set; }
        public Nullable<int> letterUp { get; set; }
        public Nullable<int> letterLevel { get; set; }
        public string letterLanguage { get; set; }
        public string senderIP { get; set; }
        public string senderCountry { get; set; }
        public string senderRegion { get; set; }
        public string senderCity { get; set; }
        public Nullable<int> letterComments { get; set; }
        public Nullable<long> toFacebookUID { get; set; }
        public Nullable<long> fromFacebookUID { get; set; }
    }
}
