//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letterstocrushes.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public int locId { get; set; }
        public string country { get; set; }
        public string region { get; set; }
        public string city { get; set; }
        public string postalCode { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<int> dmaCode { get; set; }
        public Nullable<int> areaCode { get; set; }
    }
}
