//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letterstocrushes.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class passwordchange
    {
        public int changeid { get; set; }
        public string cguid { get; set; }
        public string userguid { get; set; }
        public System.DateTime created { get; set; }
    }
}
