//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letterstocrushes.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pothole
    {
        public int PotholeId { get; set; }
        public System.DateTime DateAdd { get; set; }
        public System.DateTime DateRevised { get; set; }
        public string SubmitterName { get; set; }
        public string SubmitterIP { get; set; }
        public string Comment { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> DisplayStatus { get; set; }
        public string Address0 { get; set; }
        public Nullable<int> TownId { get; set; }
    }
}
