//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letterstocrushes.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queued
    {
        public int QueueID { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> LetterID { get; set; }
        public Nullable<System.DateTime> AddedToQueueDate { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    }
}
