//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letterstocrushes.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class song
    {
        public int id { get; set; }
        public int hearts { get; set; }
        public string youtube_id { get; set; }
        public System.DateTime date_posted { get; set; }
        public string user_ip { get; set; }
        public int status { get; set; }
    }
}
