//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letterstocrushes.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class top_list
    {
        public long letterID { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public System.DateTime letterPostDate { get; set; }
        public string letterMessage { get; set; }
        public int letterLevel { get; set; }
    }
}
